[[flavour]]
name = 'amd64'
[flavour.defs]
is_default = true
[flavour.build]
config = [
    'amd64/intel/bt.cfg',
    'amd64/intel/camera.cfg',
    'amd64/intel/cert.cfg',
    'amd64/intel/debug.cfg',
    'amd64/intel/dma.cfg',
    'amd64/intel/drm.cfg',
    'amd64/intel/edac.cfg',
    'amd64/intel/ethernet.cfg',
    'amd64/intel/features.cfg',
    'amd64/intel/fw.cfg',
    'amd64/intel/hid.cfg',
    'amd64/intel/idxd.cfg',
    'amd64/intel/intel-iommu.cfg',
    'amd64/intel/intel_th.cfg',
    'amd64/intel/ipu.cfg',
    'amd64/intel/lpss.cfg',
    'amd64/intel/nmi.cfg',
    'amd64/intel/npu.cfg',
    'amd64/intel/perf.cfg',
    'amd64/intel/pks.cfg',
    'amd64/intel/pmc_core.cfg',
    'amd64/intel/pmt.cfg',
    'amd64/intel/security.cfg',
    'amd64/intel/sof.cfg',
    'amd64/intel/tbt.cfg',
    'amd64/intel/tgpio.cfg',
    'amd64/intel/thermal.cfg',
    'amd64/intel/uncoref.cfg',
    'amd64/intel/wifivpro.cfg',
]
[flavour.description]
hardware = '64-bit PCs'
hardware_long = 'PCs with AMD64, Intel 64 or VIA Nano processors'
[flavour.packages]
installer = false

[[flavour]]
name = 'rt-amd64'
[flavour.build]
config = [
    'amd64/intel/bt.cfg',
    'amd64/intel/camera.cfg',
    'amd64/intel/cert.cfg',
    'amd64/intel/debug.cfg',
    'amd64/intel/dma.cfg',
    'amd64/intel/drm.cfg',
    'amd64/intel/edac.cfg',
    'amd64/intel/ethernet.cfg',
    'amd64/intel/features.cfg',
    'amd64/intel/fw.cfg',
    'amd64/intel/hid.cfg',
    'amd64/intel/idxd.cfg',
    'amd64/intel/intel-iommu.cfg',
    'amd64/intel/intel_th.cfg',
    'amd64/intel/ipu.cfg',
    'amd64/intel/lpss.cfg',
    'amd64/intel/nmi.cfg',
    'amd64/intel/npu.cfg',
    'amd64/intel/perf.cfg',
    'amd64/intel/pks.cfg',
    'amd64/intel/pmc_core.cfg',
    'amd64/intel/pmt.cfg',
    'amd64/intel/security.cfg',
    'amd64/intel/sof.cfg',
    'amd64/intel/tbt.cfg',
    'amd64/intel/tgpio.cfg',
    'amd64/intel/thermal.cfg',
    'amd64/intel/uncoref.cfg',
    'amd64/intel/wifivpro.cfg',
    'config.rt',
]
[flavour.description]
hardware = '64-bit PCs'
hardware_long = 'PCs with AMD64, Intel 64 or VIA Nano processors'
parts = ['rt']

[[flavour]]
name = 'test'
[flavour.build]
config = [
    'amd64/intel/bt.cfg',
    'amd64/intel/camera.cfg',
    'amd64/intel/cert.cfg',
    'amd64/intel/debug.cfg',
    'amd64/intel/dma.cfg',
    'amd64/intel/drm.cfg',
    'amd64/intel/edac.cfg',
    'amd64/intel/ethernet.cfg',
    'amd64/intel/features.cfg',
    'amd64/intel/fw.cfg',
    'amd64/intel/hid.cfg',
    'amd64/intel/idxd.cfg',
    'amd64/intel/intel-iommu.cfg',
    'amd64/intel/intel_th.cfg',
    'amd64/intel/ipu.cfg',
    'amd64/intel/lpss.cfg',
    'amd64/intel/nmi.cfg',
    'amd64/intel/npu.cfg',
    'amd64/intel/perf.cfg',
    'amd64/intel/pks.cfg',
    'amd64/intel/pmc_core.cfg',
    'amd64/intel/pmt.cfg',
    'amd64/intel/security.cfg',
    'amd64/intel/sof.cfg',
    'amd64/intel/tbt.cfg',
    'amd64/intel/tgpio.cfg',
    'amd64/intel/thermal.cfg',
    'amd64/intel/uncoref.cfg',
    'amd64/intel/wifivpro.cfg',
    'config.test',
    'amd64/config.test',
]
[flavour.defs]
is_test = true
[flavour.packages]
installer = false

[[featureset]]
name = 'none'

[build]
enable_rust = true
enable_signed = false
kernel_file = 'arch/x86/boot/bzImage'
kernel_stem = 'vmlinuz'

[relations.image]
suggests = ['grub-pc | grub-efi-amd64 | extlinux']
