#!/bin/sh

set -e

old_version_suffix="$(echo "$2" | sed -rn 's/^([0-9]+\.[0-9]+).*/\1/p')"
if [ "$old_version_suffix" ]; then
    dpkg-maintscript-helper symlink_to_dir \
	/usr/share/doc/linux-intel-perf "linux-intel-perf-${old_version_suffix}" 5.16\~rc8-1\~exp1 linux-intel-perf -- "$@"
fi

if [ "$1" = remove ]
then
	for wrapper in /usr/bin/perf \
		       /usr/share/bash-completion/completions/perf \
		       /usr/share/man/man1/perf.1.gz; do
	    diversion="${wrapper%/perf*}/perf.wrapper${wrapper#*/perf}"
fi

#DEBHELPER#
