# amd64 only kernel configuration

[[kernelarch]]
name = 'x86'
  [[kernelarch.debianarch]]
  name = 'amd64'

[[featureset]]
name = 'none'

[[debianrelease]]
name_regex = 'intel'
abi_version_full = true
abi_suffix = '-intel+TIMESTAMP'

[[debianrelease]]
name_regex = 'UNRELEASED'
abi_version_full = true
abi_suffix = ''

[[debianrelease]]
name_regex = 'oracular'
abi_suffix = '+ubuntu24.10'
revision_regex = '\d+(\.\d+)?'

# Use default rules for any suite with no explicit config
[[debianrelease]]
name_regex = '.*'

[description.long]
rt = 'This kernel is configured with PREEMPT_RT real time support.'
[description.short]
rt = 'PREEMPT_RT'

[build]
c_compiler = 'gcc-14'
# Rust dependencies disabled for Ubuntu 24.04 LTS compatibility
# rust_build_depends = [
#   'rustc:native (>= 1.78.0)',
#   'bindgen:native (>= 0.65.1)',
#   'rust-src (>= 1.78.0)',
# ]

[relations.image]
depends = [
  'dracut | initramfs-tools (>= 0.120+deb8u2) | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
